server:
    port: 5003
spring:
    data:
        mongodb:
            authentication-database: examples
            database: examples
            username: api_user
            password: NdEep0XLpMNKUmgQVa81oDCx7mrSRodh0Z79qdX3
            host: localhost
            port: 30001
    kafka:
        bootstrap-servers: localhost:29092
        consumer:
            group-id: test-consumer-group
    application:
        name: transaction-query
message:
    topic:
        createTransaction: create-transaction
        updateTransaction: update-transaction